version: '3.8'

services:
  nginx:
    image: nginx:1.25
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8900:80"
    container_name: nginx
  phpfpm:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/
      - postgres:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql
    container_name: phpfpm
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=laravel
    ports:
      - '8901:5432'
    volumes: 
      - ./docker/db:/var/lib/postgresql/data
    container_name: postgres
volumes:
  postgres:
    driver: local

